# Site settings
title: smallmuou blog
motto: 我虽小，但我却能留下您的足迹
email: lvyexuwenfa100@126.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wenva.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  smallmuou

# Build settings
markdown: kramdown
